#!/usr/bin/env python3

import os, sys
import time

from argparse import ArgumentParser

from serialtalks import SerialTalks
from components  import Server


def getuuid(args):
	talks = SerialTalks(args.port)
	try:
		talks.connect(args.timeout)
		uuid = talks.getuuid(args.timeout)
		if isinstance(uuid, str):
			print(uuid)
		else:
			raise ValueError('\'{}\' object is not a valid UUID'.format(type(uuid)))
	except KeyboardInterrupt:
		pass
	finally:
		talks.disconnect()


def getlogs(args):
	talks = SerialTalks(args.port)
	try:
		talks.connect(args.timeout)
		while True:
			sys.stdout.write(talks.getout())
			sys.stderr.write(talks.geterr())
	except KeyboardInterrupt:
		pass
	finally:
		talks.disconnect()


def server(args):
	srv = Server(password=args.password)
	while True:
		try:
			if not srv.is_connected:
				srv.connect(None)
			else:
				srv.sleep_until_disconnected()
		except KeyboardInterrupt:
			srv.disconnect()
			break
		except Exception as e:
			sys.stderr.write('{}: {}\n'.format(type(e).__name__, e))
			continue

parser = ArgumentParser()
subparsers = parser.add_subparsers()

getuuid_parser = subparsers.add_parser('getuuid')
getuuid_parser.add_argument('port', type=str)
getuuid_parser.add_argument('-t', '--timeout', type=float, default=2)
getuuid_parser.set_defaults(func=getuuid)

getlogs_parser = subparsers.add_parser('getlogs')
getlogs_parser.add_argument('port', type=str)
getlogs_parser.add_argument('-t', '--timeout', type=float, default=2)
getlogs_parser.set_defaults(func=getlogs)

modulesrouter_parser = subparsers.add_parser('server')
modulesrouter_parser.add_argument('-p', '--password', type=str, default=None)
modulesrouter_parser.set_defaults(func=server)

args = parser.parse_args()
args.func(args)

