#ifndef __ADDRESSES_H__
#define __ADDRESSES_H__

#define LINEAR_VELOCITY_PID_ADDRESS  0x040
#define ANGULAR_VELOCITY_PID_ADDRESS 0x060

#define LINEAR_POSITION_PID_ADDRESS  0x080
#define ANGULAR_POSITION_PID_ADDRESS 0x0A0

#define LINEAR_POSITION_TO_VELOCITY_PID_ADDRESS  0x0C0
#define ANGULAR_POSITION_TO_VELOCITY_PID_ADDRESS 0x0E0

#endif // __ADDRESSES_H__
