#!/usr/bin/env python3

import sys
import time
from serialtalks import SerialTalks

refresh = 60

port = sys.argv[1]
try:
	with SerialTalks(port) as talks:
		while True:
			print(talks.getout(), end = '')
			print(talks.geterr(), end = '')
			time.sleep(1 / refresh)

except KeyboardInterrupt:
	sys.exit(0)	
